### PR TITLE
AWS Migration

### PR DESCRIPTION
**Pull request by SeanSCao**

### CODE REVIEW

**Comment by dhanrajteqfocus002** [comment]
i am able to build docker image after the changes and looks good to me. i am not sure whether i should approve this PR or not.
i am not sure  if this changes doesn't effect any thing else.
cc: @davestern

**Review by dhanrajteqfocus002 — APPROVED** [review]
Looks good.

**Comment by dhanrajteqfocus002** [comment]
This PR has been approved. @SeanSCao Please merge this code.

**Comment by davestern** [comment]
@SeanSCao and @dhanrajteqfocus002. For future reference, this branch did not need to be merged to use it. You can rebase a feature branch onto any other branch before it's merged to get the commits and use them. That's a better way to go than forcing a merge before it's ready.

Also, this branch could have been named better :-)

**Pull request merged**
